% chirp signal generation
% https://uk.mathworks.com/help/thingspeak/remove-dc-component-and-display-results.html

hchirp = dsp.Chirp( ...
    'InitialFrequency', 0,...
    'TargetFrequency', 1000, ...
    'TargetTime', 10, ...
    'SweepTime', 100, ...
    'SampleRate', 2000, ...
    'SamplesPerFrame', 10000);
chirpData = (step(hchirp))';
% evenFlag = mod(minute(datetime('now')),2); % do not need this part
% if evenFlag
%     chirpData = fliplr(chirpData);
% end
plot(chirpData);