% https://uk.mathworks.com/help/matlab/import_export/record-and-play-audio.html
recObj = audiorecorder(44100,16,1);

recDuration = 5;
disp("Begin speaking.")
recordblocking(recObj,recDuration);
disp("End of recording.")
play(recObj);
y = getaudiodata(recObj);
plot(y);
info = audiodevinfo;
audiowrite("Speech.wav", y, 44100, "Title", "Speech", "Artist", "PeterS", "Comment", "Generated by MatLab");
